---

network: testnet
vault_enabled: "{{ vault_path is not none }}"
vault_mount_point: "kv"
vault_namespace: "eng/blockchain"
vault_path: "validators/solana/{{ network }}/validator"
vault_full_path: "{{ vault_mount_point }}/{{ vault_path }}"

vault_secret: >-
  {{ lookup(
      "community.hashi_vault.vault_kv2_get",
      vault_path,
      mount_point=vault_mount_point,
      engine_mount_point=vault_mount_point,
      namespace=vault_namespace,
      auth_method="token",
      validate_certs=False
    ) if vault_enabled else none
  }}

staked_identity: >-
  {{ vault_secret.data.data['identity.json']
  if vault_enabled
  else none
  }}
