---

solana_network: testnet

solana_vault_enabled: "{{ solana_vault_path is not none }}"
solana_vault_path: "kv/validators/solana/{{ solana_network }}/validator"
solana_vault_namespace: "eng/blockchain/"
# solana_vault_mount_point: blockchain-secrets
solana_vault_mount_point: "{{ solana_vault_namespace }}/{{ solana_vault_path }}"

solana_vault_secret: >-
  {{ lookup(
      "community.hashi_vault.vault_kv2_get",
      solana_vault_path,
      mount_point=solana_vault_mount_point,
      engine_mount_point=solana_vault_mount_point,
      auth_method="token",
      validate_certs=False
    ) if solana_vault_enabled else none
  }}

solana_staked_identity: >-
  {{ solana_vault_secret.data.data.validator
  if solana_vault_enabled
  else none
  }}
