---
collections:
  - name: "community.general"
    version: "10.3.0"

  - name: "ansible.posix"
    version: "1.6.2"

  - name: "containers.podman"
    version: "1.16.3"

  - name: "community.postgresql"
    version: "3.12.0"

  - name: "community.hashi_vault"
    version: "7.0.0"

  - name: "grafana.grafana"
    version: "5.7.0"

  - name: "pureport.fabric"
    version: "1.0.0"

  - name: "community.digitalocean"
    version: "1.27.0"
