---
mdadm_arrays:
  md4:
    drives:
      - "/dev/nvme0n1"
      - "/dev/nvme1n1"
    level: "raid1"
  md5:
    drives:
      - "/dev/nvme3n1"
      - "/dev/nvme4n1"
    level: "raid1"

filesystems:
  md4:
    partitions:
      - name: "md4p1"
        partition_name: "solana"
        fstype: ext4
        opts: defaults
        label: solana
        size: 100%
        mount_point: "{{ solana_mount_path }}"
  md5:
    partitions:
      - name: "md5p1"
        partition_name: "ledger"
        fstype: ext4
        opts: defaults
        label: ledger
        size: 100%
        mount_point: "{{ solana_mount_path }}/ledger"

solana_mount_path: "/mnt/solana"
solana_log_path: "{{ solana_mount_path }}/logs/firedancer.log"
solana_snapshot_fetch: false

logrotate_paths:
  solana:
    path: "{{ solana_log_path | dirname }}"
    delaycompress: false
    owner: sol
    group: sol

solana_swap_file_path: "{{ solana_mount_path }}/swapfile"
solana_swap_size_gb: 64

solana_snapshot_path: "{{ solana_ledger_path }}/snapshots"

solana_firedancer_tuned_config:
  layout:
    affinity: "0-39"
    agave_affinity: "40-127"
    agave_unified_scheduler_handler_threads: 32
    net_tile_count: 1
    quic_tile_count: 1
    resolv_tile_count: 1
    verify_tile_count: 8
    bank_tile_count: 20
    shred_tile_count: 1
  net:
    ingress_buffer_size: 8192
    xdp:
      xdp_rx_queue_size: 8192
      xdp_tx_queue_size: 2048
      flush_timeout_micros: 10
  snapshots:
    minimum_snapshot_download_speed: 20971520
    path: "{{ solana_snapshot_path }}"
    incremental_path: "{{ solana_snapshot_path }}"
  hugetlbfs:
    mount_path: "{{ solana_mount_path }}/.fd"
  tiles:
    quic:
      max_concurrent_connections: 262144
      txn_reassembly_count: 262144
      max_concurrent_handshakes: 8192
      ack_delay_millis: 25
    verify:
      signature_cache_size: 8388606
      receive_buffer_size: 32768
    shred:
      max_pending_shred_sets: 1024
    pack:
      schedule_strategy: "revenue"
