---
# - name: Update all packages
#   ansible.builtin.import_tasks: updates.yml
#   tags: ["packages:updates", "never"]

- name: List all installed packages
  ansible.builtin.import_tasks: list.yml
  tags: ["packages:list"]
