---
solana_firedancer_version: "0.707.20306-testnet"

solana_network: testnet

solana_vault_enabled: "{{ solana_vault_path is not none }}"

solana_vault_mount_point: blockchain-secrets

# solana_vault_path: "solana/{{ solana_network }}/private-keys"
solana_vault_path: "{{ solana_vault_mount_point }}/solana/{{ solana_network }}"

solana_vault_list: >-
  {{ lookup(
      "community.hashi_vault.vault_list",
        solana_vault_path,
        namespace=solana_vault_mount_point,
        auth_method="token",
        validate_certs=False
    ) if solana_vault_enabled else none
  }}

# solana_vault_secret: >-
#   {{ lookup(
#       "community.hashi_vault.vault_kv2_get",
#         auth_method="token",
#         path=solana_vault_path,
#         namespace=solana_vault_mount_point,
#         validate_certs=False
#     ) if solana_vault_enabled else none
#   }}

# solana_staked_identity: >-
#   {{ solana_vault_secret.data.validator
#   if solana_vault_enabled
#   else none
#   }}
