---
solana_firedancer_version: "0.707.20306-testnet"

solana_network: testnet

solana_vault_path: "solana/{{ solana_network }}/private-keys"

solana_vault_enabled: "{{ solana_vault_path is not none }}"

solana_vault_path: null

solana_vault_mount_point: secrets

solana_vault_secret: >-
  {{ lookup(
      "community.hashi_vault.vault_kv2_get",
      solana_vault_path,
      engine_mount_point="blockchain-secrets",
      validate_certs=False
    ) if solana_vault_enabled else none
  }}

solana_staked_identity: >-
  {{ solana_vault_secret.data.data.validator
  if solana_vault_enabled
  else none
  }}

